import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from "node:fs";
import { join, dirname } from "node:path";
import { tmpdir } from "node:os";
import { buildIdentity } from "../scripts/build-identity.mjs";

test("release fingerprint agrees across clean checkouts, line endings and generated Android config", (t) => {
  const root = mkdtempSync(join(tmpdir(), "pulse-fingerprint-"));
  t.after(() => rmSync(root, { recursive: true, force: true }));
  const roots = [join(root, "windows"), join(root, "linux")];
  for (const [i, dir] of roots.entries()) {
    for (const folder of ["src", "shared", "public", "desktop", "server", "android/app/src/main/java", "android/app/src/main/res"])
      mkdirSync(join(dir, folder), { recursive: true });
    for (const file of ["index.html", "package.json", "package-lock.json", "vite.config.js", "android/app/build.gradle", "android/app/src/main/AndroidManifest.xml", "public/license.txt", "src/App.jsx"]) {
      const path = join(dir, file);
      mkdirSync(dirname(path), { recursive: true });
      writeFileSync(path, (file === "package.json" ? '{"version":"1.0.4"}' : "same source") + (i ? "\n" : "\r\n"));
    }
  }
  mkdirSync(join(roots[0], "android/app/src/main/res/xml"));
  writeFileSync(join(roots[0], "android/app/src/main/res/xml/config.xml"), "generated by Capacitor");
  assert.deepEqual(buildIdentity(roots[0]), buildIdentity(roots[1]));
  writeFileSync(join(roots[1], "src/App.jsx"), "new interface\n");
  assert.notEqual(buildIdentity(roots[0]).sourceHash, buildIdentity(roots[1]).sourceHash);
});
