package app.pulse.status;

/** Generated by scripts/generate-native-catalog.mjs. Do not edit. */
final class PulseIcons {
    private PulseIcons() {}
    static int drawable(String id) {
        switch(id) {
            case "npm": return R.drawable.ic_provider_npm;
            case "pypi": return R.drawable.ic_provider_pypi;
            case "docker": return R.drawable.ic_provider_docker;
            case "rubygems": return R.drawable.ic_provider_rubygems;
            case "circleci": return R.drawable.ic_provider_circleci;
            case "postman": return R.drawable.ic_provider_postman;
            case "sentry": return R.drawable.ic_provider_sentry;
            case "snyk": return R.drawable.ic_provider_snyk;
            case "hackerone": return R.drawable.ic_provider_hackerone;
            case "openai": return R.drawable.ic_provider_openai;
            case "anthropic": return R.drawable.ic_provider_anthropic;
            case "cloudflare": return R.drawable.ic_provider_cloudflare;
            case "aws": return R.drawable.ic_provider_aws;
            case "googlecloud": return R.drawable.ic_provider_googlecloud;
            case "azure": return R.drawable.ic_provider_azure;
            case "github": return R.drawable.ic_provider_github;
            case "vercel": return R.drawable.ic_provider_vercel;
            case "supabase": return R.drawable.ic_provider_supabase;
            case "digitalocean": return R.drawable.ic_provider_digitalocean;
            case "render": return R.drawable.ic_provider_render;
            case "netlify": return R.drawable.ic_provider_netlify;
            case "huggingface": return R.drawable.ic_provider_huggingface;
            case "replicate": return R.drawable.ic_provider_replicate;
            case "discord": return R.drawable.ic_provider_discord;
            case "zoom": return R.drawable.ic_provider_zoom;
            case "twilio": return R.drawable.ic_provider_twilio;
            case "atlassian": return R.drawable.ic_provider_atlassian;
            case "notion": return R.drawable.ic_provider_notion;
            case "railway": return R.drawable.ic_provider_railway;
            case "godaddy": return R.drawable.ic_provider_godaddy;
            case "hostinger": return R.drawable.ic_provider_hostinger;
            case "groq": return R.drawable.ic_provider_groq;
            case "nvidia": return R.drawable.ic_provider_nvidia;
            case "googleaistudio": return R.drawable.ic_provider_googleaistudio;
            case "cohere": return R.drawable.ic_provider_cohere;
            case "perplexity": return R.drawable.ic_provider_perplexity;
            case "elevenlabs": return R.drawable.ic_provider_elevenlabs;
            case "fireworks": return R.drawable.ic_provider_fireworks;
            case "pinecone": return R.drawable.ic_provider_pinecone;
            case "deepgram": return R.drawable.ic_provider_deepgram;
            case "assemblyai": return R.drawable.ic_provider_assemblyai;
            case "baseten": return R.drawable.ic_provider_baseten;
            case "scaleai": return R.drawable.ic_provider_scaleai;
            case "stabilityai": return R.drawable.ic_provider_stabilityai;
            case "snowflake": return R.drawable.ic_provider_snowflake;
            case "mongodbatlas": return R.drawable.ic_provider_mongodbatlas;
            case "clickhouse": return R.drawable.ic_provider_clickhouse;
            case "upstash": return R.drawable.ic_provider_upstash;
            case "planetscale": return R.drawable.ic_provider_planetscale;
            case "elasticcloud": return R.drawable.ic_provider_elasticcloud;
            case "bitbucket": return R.drawable.ic_provider_bitbucket;
            case "flyio": return R.drawable.ic_provider_flyio;
            case "akamai": return R.drawable.ic_provider_akamai;
            case "bunny": return R.drawable.ic_provider_bunny;
            case "datadog": return R.drawable.ic_provider_datadog;
            case "newrelic": return R.drawable.ic_provider_newrelic;
            case "grafana": return R.drawable.ic_provider_grafana;
            case "buildkite": return R.drawable.ic_provider_buildkite;
            case "hashicorp": return R.drawable.ic_provider_hashicorp;
            case "pulumi": return R.drawable.ic_provider_pulumi;
            case "clerk": return R.drawable.ic_provider_clerk;
            case "workos": return R.drawable.ic_provider_workos;
            case "codecov": return R.drawable.ic_provider_codecov;
            case "travisci": return R.drawable.ic_provider_travisci;
            case "jfrog": return R.drawable.ic_provider_jfrog;
            case "shopify": return R.drawable.ic_provider_shopify;
            case "plaid": return R.drawable.ic_provider_plaid;
            case "wise": return R.drawable.ic_provider_wise;
            case "bigcommerce": return R.drawable.ic_provider_bigcommerce;
            case "mailgun": return R.drawable.ic_provider_mailgun;
            case "resend": return R.drawable.ic_provider_resend;
            case "figma": return R.drawable.ic_provider_figma;
            case "dropbox": return R.drawable.ic_provider_dropbox;
            case "box": return R.drawable.ic_provider_box;
            case "hubspot": return R.drawable.ic_provider_hubspot;
            case "linear": return R.drawable.ic_provider_linear;
            case "zapier": return R.drawable.ic_provider_zapier;
            default: return R.drawable.ic_pulse_notification_logo;
        }
    }
}
