package app.pulse.status;

/** Generated by scripts/generate-native-catalog.mjs. Do not edit. */
final class PulseIcons {
    private PulseIcons() {}
    static int drawable(String id) {
        switch(id) {
            case "npm": return R.drawable.ic_provider_npm;
            case "pypi": return R.drawable.ic_provider_pypi;
            case "docker": return R.drawable.ic_provider_docker;
            case "rubygems": return R.drawable.ic_provider_rubygems;
            case "circleci": return R.drawable.ic_provider_circleci;
            case "postman": return R.drawable.ic_provider_postman;
            case "sentry": return R.drawable.ic_provider_sentry;
            case "snyk": return R.drawable.ic_provider_snyk;
            case "hackerone": return R.drawable.ic_provider_hackerone;
            case "openai": return R.drawable.ic_provider_openai;
            case "anthropic": return R.drawable.ic_provider_anthropic;
            case "cloudflare": return R.drawable.ic_provider_cloudflare;
            case "aws": return R.drawable.ic_provider_aws;
            case "googlecloud": return R.drawable.ic_provider_googlecloud;
            case "azure": return R.drawable.ic_provider_azure;
            case "github": return R.drawable.ic_provider_github;
            case "vercel": return R.drawable.ic_provider_vercel;
            case "supabase": return R.drawable.ic_provider_supabase;
            case "digitalocean": return R.drawable.ic_provider_digitalocean;
            case "render": return R.drawable.ic_provider_render;
            case "netlify": return R.drawable.ic_provider_netlify;
            case "huggingface": return R.drawable.ic_provider_huggingface;
            case "replicate": return R.drawable.ic_provider_replicate;
            case "discord": return R.drawable.ic_provider_discord;
            case "zoom": return R.drawable.ic_provider_zoom;
            case "twilio": return R.drawable.ic_provider_twilio;
            case "atlassian": return R.drawable.ic_provider_atlassian;
            case "notion": return R.drawable.ic_provider_notion;
            case "railway": return R.drawable.ic_provider_railway;
            case "godaddy": return R.drawable.ic_provider_godaddy;
            case "hostinger": return R.drawable.ic_provider_hostinger;
            case "groq": return R.drawable.ic_provider_groq;
            case "nvidia": return R.drawable.ic_provider_nvidia;
            case "googleaistudio": return R.drawable.ic_provider_googleaistudio;
            default: return R.drawable.ic_pulse_notification_logo;
        }
    }
}
