// Shared Phosphor vocabulary keeps sizing consistent across the application.
//
// Icons are drawn at four sizes and no others:
//   16  inline — beside body or caption text, inside chips and meta rows
//   20  control — buttons, icon buttons, list rows, navigation
//   24  section — panel and card headers, feature tiles
//   32  display — empty and quiet states
// tests/design-tokens.test.js fails the build on any other value.
export {
  PulseIcon as Activity,
  SquaresFourIcon as LayoutDashboard,
  GlobeHemisphereWestIcon as Globe2,
  BroadcastIcon as Radio,
  GraphIcon as Network,
  StarIcon as Star,
  ArrowUpRightIcon as ArrowUpRight,
  ArrowRightIcon as ArrowRight,
  ArrowLeftIcon as ArrowLeft,
  MagnifyingGlassIcon as Search,
  PlusIcon as Plus,
  BellIcon as Bell,
  CaretDownIcon as ChevronDown,
  CaretRightIcon as ChevronRight,
  CheckIcon as Check,
  QuestionIcon as CircleHelp,
  GearSixIcon as Settings,
  DownloadSimpleIcon as Download,
  XIcon as X,
  ArrowsClockwiseIcon as RefreshCw,
  ArrowSquareOutIcon as ExternalLink,
  CloudIcon as Cloud,
  GitForkIcon as GitFork,
  VideoCameraIcon as Video,
  ChatCircleIcon as MessageCircle,
  ShieldCheckIcon as ShieldCheck,
  SlidersHorizontalIcon as SlidersHorizontal,
  ListIcon as Menu,
  ChecksIcon as CheckCheck,
  WarningIcon as TriangleAlert,
  StackIcon as Layers3,
  CommandIcon as Command,
  EyeIcon as Eye,
  RadioButtonIcon as CircleDot,
  LightningIcon as Zap,
  SunIcon as Sun,
  MoonIcon as Moon,
  CopyIcon as Copy,
  TerminalWindowIcon as Terminal,
  ClockIcon as Clock3,
  PackageIcon as PackageSearch,
  FingerprintIcon as Fingerprint,
  BracketsCurlyIcon as Braces,
  MinusIcon as Minus,
  CrosshairIcon as LocateFixed,
  MapPinIcon as MapPin,
  CompassIcon as Compass,
  FunnelIcon as Funnel,
} from "@phosphor-icons/react";
